In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [2]:
df_red = pd.read_csv("winequality-red.csv", sep = ";")
df_white = pd.read_csv("winequality-white.csv", sep = ";")

In [3]:
df_red["wine type"] = 1
df_red

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  wine type  
0         9.4        5          1  
1         9.8        5          1  
2         9.8        5          1  
3         9.8        6          1  
4         9.4        5          1  
...       ...      ...        ...  
1594     10.5        5          1  
1595     11.2        6          1  
1596     11.0        6          1  
1597     10.2        5          1  
1598     11.0        6          1  

[1599 rows x 13 columns]

In [4]:
df_white["wine type"] = 0
df_white

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  wine type  
0         8.8        6          0  
1         9.5        6          0  
2        10.1        6          0  
3         9.9        6          0  
4         9.9        6          0  
...       ...      ...        ...  
4893     11.2        6          0  
4894      9.6        5          0  
4895      9.4        6          0  
4896     12.8        7          0  
4897     11.8        6          0  

[4898 rows x 13 columns]

In [5]:
df_red["quality_label"] = df_red["quality"].apply(lambda value: "0"
if value <= 5 else '1'
if value <= 7 else '2')
df_red

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  wine type quality_label  
0         9.4        5          1             0  
1         9.8        5          1             0  
2         9.8        5          1             0  
3         9.8        6          1             1  
4         9.4        5          1             0  
...       ...      ...        ...           ...  
1594     10.5        5          1             0  
1595     11.2        6          1             1  
1596     11.0        6          1             1  
1597     10.2        5          1             0  
1598     11.0        6          1             1  

[1599 rows x 14 columns]

In [6]:
df_white["quality_label"] = df_white["quality"].apply(lambda value: "0"
if value <= 5 else '1'
if value <= 7 else '2')
df_white

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  wine type quality_label  
0         8.8        6          0             1  
1         9.5        6          0             1  
2        10.1        6          0             1  
3         9.9        6          0             1  
4         9.9        6          0             1  
...       ...      ...        ...           ...  
4893     11.2        6          0             1  
4894      9.6        5          0             0  
4895      9.4        6          0             1  
4896     12.8        7          0             1  
4897     11.8        6          0             1  

[4898 rows x 14 columns]

# Machine learning modell with logistic regression

 Goal is:  determine the wine type(white is 0, red is 1) from the different composition with logisitic regression

to prepare the dataframe: concatenate white and red wine dataframe

In [7]:
df = pd.concat([df_red,df_white], axis = 0, ignore_index=True)
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4              0.70         0.00             1.9      0.076   
1               7.8              0.88         0.00             2.6      0.098   
2               7.8              0.76         0.04             2.3      0.092   
3              11.2              0.28         0.56             1.9      0.075   
4               7.4              0.70         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
6492            6.2              0.21         0.29             1.6      0.039   
6493            6.6              0.32         0.36             8.0      0.047   
6494            6.5              0.24         0.19             1.2      0.041   
6495            5.5              0.29         0.30             1.1      0.022   
6496            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
6492                 24.0                  92.0  0.99114  3.27       0.50   
6493                 57.0                 168.0  0.99490  3.15       0.46   
6494                 30.0                 111.0  0.99254  2.99       0.46   
6495                 20.0                 110.0  0.98869  3.34       0.38   
6496                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  wine type quality_label  
0         9.4        5          1             0  
1         9.8        5          1             0  
2         9.8        5          1             0  
3         9.8        6          1             1  
4         9.4        5          1             0  
...       ...      ...        ...           ...  
6492     11.2        6          0             1  
6493      9.6        5          0             0  
6494      9.4        6          0             1  
6495     12.8        7          0             1  
6496     11.8        6          0             1  

[6497 rows x 14 columns]

2. split the data into train data and test data

In [25]:
# X are the variables used to predict the wine type.
# y is the prediction variable. 

X = df[["fixed acidity", "volatile acidity", "citric acid", "residual sugar", "chlorides", "free sulfur dioxide",
               "total sulfur dioxide", "density", "pH", "sulphates", "alcohol", "quality"]]
y = df["wine type"]

In [26]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         6497 non-null   float64
 1   volatile acidity      6497 non-null   float64
 2   citric acid           6497 non-null   float64
 3   residual sugar        6497 non-null   float64
 4   chlorides             6497 non-null   float64
 5   free sulfur dioxide   6497 non-null   float64
 6   total sulfur dioxide  6497 non-null   float64
 7   density               6497 non-null   float64
 8   pH                    6497 non-null   float64
 9   sulphates             6497 non-null   float64
 10  alcohol               6497 non-null   float64
 11  quality               6497 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 609.2 KB


In [27]:
X.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [28]:
y

0       1
1       1
2       1
3       1
4       1
       ..
6492    0
6493    0
6494    0
6495    0
6496    0
Name: wine type, Length: 6497, dtype: int64

In [29]:
# Split the data to test and train
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
display(X_train.head(2))
display(X_test.head(2))
display(y_train.head(2))
display(y_test.head(2))

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1916            6.6              0.24         0.35             7.7      0.031   
947             8.3              0.28         0.48             2.1      0.093   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1916                 36.0                 135.0  0.99380  3.19       0.37   
947                   6.0                  12.0  0.99408  3.26       0.62   

      alcohol  quality  
1916     10.5        5  
947      12.4        7

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
3103            7.0              0.17         0.74            12.8      0.045   
1419            7.7              0.64         0.21             2.2      0.077   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
3103                 24.0                 126.0   0.9942  3.26       0.38   
1419                 32.0                 133.0   0.9956  3.27       0.45   

      alcohol  quality  
3103     12.2        8  
1419      9.9        5

1916    0
947     1
Name: wine type, dtype: int64

3103    0
1419    1
Name: wine type, dtype: int64

3. Normalizse or Standardize the train and test after splitting. 

In [30]:
# data normalization with sklearn
from sklearn.preprocessing import MinMaxScaler

# fit scaler on training data
norm = MinMaxScaler().fit(X_train)

# transform training data
X_train_norm = norm.transform(X_train)

# transform testing dataabs
X_test_norm = norm.transform(X_test)

print(norm)
print(X_train_norm)
print(X_test_norm)

MinMaxScaler()
[[0.23728814 0.10666667 0.28455285 ... 0.08426966 0.40322581 0.33333333]
 [0.38135593 0.13333333 0.3902439  ... 0.2247191  0.70967742 0.66666667]
 [0.33050847 0.42333333 0.00813008 ... 0.19662921 0.61290323 0.5       ]
 ...
 [0.22033898 0.19333333 0.16260163 ... 0.11797753 0.24193548 0.33333333]
 [0.22881356 0.12       0.40650407 ... 0.14044944 0.24193548 0.33333333]
 [0.28813559 0.36       0.04878049 ... 0.17977528 0.24193548 0.33333333]]
[[0.27118644 0.06       0.60162602 ... 0.08988764 0.67741935 0.83333333]
 [0.33050847 0.37333333 0.17073171 ... 0.12921348 0.30645161 0.33333333]
 [0.25423729 0.20666667 0.27642276 ... 0.12359551 0.64516129 0.66666667]
 ...
 [0.23728814 0.05333333 0.28455285 ... 0.29775281 0.70967742 0.66666667]
 [0.23728814 0.20666667 0.30894309 ... 0.19662921 0.22580645 0.5       ]
 [0.30508475 0.05333333 0.2195122  ... 0.11797753 0.11290323 0.66666667]]



4. Fit the model

In [33]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(solver='lbfgs', max_iter=2000)
lr.fit(X_train, y_train)

LogisticRegression(max_iter=2000)

5. Make predictions

In [34]:

pred_lr = lr.predict(X_test)

6. Evaluate the model

In [35]:
from sklearn.metrics import confusion_matrix

print("Confusion matrix:")
print(confusion_matrix(y_test, pred_lr))

Confusion matrix:
[[951   8]
 [ 19 322]]


In [36]:
from sklearn.metrics import accuracy_score

print("Accuracy score:", accuracy_score(y_test, pred_lr))

Accuracy score: 0.9792307692307692


In [37]:
from sklearn.metrics import classification_report

print(classification_report(y_test, pred_lr, target_names=["White","red"]))

              precision    recall  f1-score   support

         Red       0.98      0.99      0.99       959
       White       0.98      0.94      0.96       341

    accuracy                           0.98      1300
   macro avg       0.98      0.97      0.97      1300
weighted avg       0.98      0.98      0.98      1300



In [63]:
# with all variables

X = df[["fixed acidity", "volatile acidity", "citric acid", "residual sugar", "chlorides", "free sulfur dioxide",
               "total sulfur dioxide", "density", "pH", "sulphates", "alcohol", "quality"]]
y = df["wine type"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

norm = MinMaxScaler().fit(X_train)
# transform training data
X_train_norm = norm.transform(X_train)
# transform testing data
X_test_norm = norm.transform(X_test)

lr = LogisticRegression(solver='lbfgs', max_iter=2000)
lr.fit(X_train, y_train)
pred_lr = lr.predict(X_test)

print("result without acidity variables: ")
print("Confusion matrix:")
print(confusion_matrix(y_test, pred_lr))
print("Accuracy score:", accuracy_score(y_test, pred_lr))
print(classification_report(y_test, pred_lr, target_names=["White","Red"]))

result without acidity variables: 
Confusion matrix:
[[951   8]
 [ 19 322]]
Accuracy score: 0.9792307692307692
              precision    recall  f1-score   support

       White       0.98      0.99      0.99       959
         Red       0.98      0.94      0.96       341

    accuracy                           0.98      1300
   macro avg       0.98      0.97      0.97      1300
weighted avg       0.98      0.98      0.98      1300



In [62]:
# without acidity variables ("fixed acidity", "volatile acidity", "citric acid", )

X = df[["residual sugar", "chlorides", "free sulfur dioxide",
               "total sulfur dioxide", "density", "pH", "sulphates", "alcohol", "quality"]]
y = df["wine type"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

norm = MinMaxScaler().fit(X_train)
# transform training data
X_train_norm = norm.transform(X_train)
# transform testing data
X_test_norm = norm.transform(X_test)

lr = LogisticRegression(solver='lbfgs', max_iter=2000)
lr.fit(X_train, y_train)
pred_lr = lr.predict(X_test)

print("result without acidity variables: ")
print("Confusion matrix:")
print(confusion_matrix(y_test, pred_lr))
print("Accuracy score:", accuracy_score(y_test, pred_lr))
print(classification_report(y_test, pred_lr, target_names=["White","Red"]))


result without acidity variables: 
Confusion matrix:
[[943  16]
 [ 39 302]]
Accuracy score: 0.9576923076923077
              precision    recall  f1-score   support

       White       0.96      0.98      0.97       959
         Red       0.95      0.89      0.92       341

    accuracy                           0.96      1300
   macro avg       0.95      0.93      0.94      1300
weighted avg       0.96      0.96      0.96      1300



In [56]:
# without sulfur variables ("free sulfur dioxide", "total sulfur dioxide" )

X = df[["fixed acidity", "volatile acidity", "citric acid", "residual sugar", "chlorides", "density", 
      "pH", "sulphates", "alcohol", "quality"]]
y = df["wine type"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

norm = MinMaxScaler().fit(X_train)
# transform training data
X_train_norm = norm.transform(X_train)
# transform testing dataabs
X_test_norm = norm.transform(X_test)

lr = LogisticRegression(solver='lbfgs', max_iter=2000)
lr.fit(X_train, y_train)
pred_lr = lr.predict(X_test)

print("result without sulfur variables: ")
print("Confusion matrix:")
print(confusion_matrix(y_test, pred_lr))
print("Accuracy score:", accuracy_score(y_test, pred_lr))
print(classification_report(y_test, pred_lr, target_names=["Red","White"]))

result without sulfur variables: 
Confusion matrix:
[[943  16]
 [ 22 319]]
Accuracy score: 0.9707692307692307
              precision    recall  f1-score   support

         Red       0.98      0.98      0.98       959
       White       0.95      0.94      0.94       341

    accuracy                           0.97      1300
   macro avg       0.96      0.96      0.96      1300
weighted avg       0.97      0.97      0.97      1300



In [57]:
# without sulfur variables and chlorides variable ("free sulfur dioxide", "total sulfur dioxide", "chlorides" )

X = df[["fixed acidity", "volatile acidity", "citric acid", "residual sugar", "density", 
      "pH", "sulphates", "alcohol", "quality"]]
y = df["wine type"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

norm = MinMaxScaler().fit(X_train)
# transform training data
X_train_norm = norm.transform(X_train)
# transform testing dataabs
X_test_norm = norm.transform(X_test)

lr = LogisticRegression(solver='lbfgs', max_iter=2000)
lr.fit(X_train, y_train)
pred_lr = lr.predict(X_test)

print("result without sulfur variables: ")
print("Confusion matrix:")
print(confusion_matrix(y_test, pred_lr))
print("Accuracy score:", accuracy_score(y_test, pred_lr))
print(classification_report(y_test, pred_lr, target_names=["White","Red"]))

result without sulfur variables: 
Confusion matrix:
[[941  18]
 [ 22 319]]
Accuracy score: 0.9692307692307692
              precision    recall  f1-score   support

       White       0.98      0.98      0.98       959
         Red       0.95      0.94      0.94       341

    accuracy                           0.97      1300
   macro avg       0.96      0.96      0.96      1300
weighted avg       0.97      0.97      0.97      1300



In [59]:
# without sulfur variables and chlorides variable ("free sulfur dioxide", "total sulfur dioxide", "chlorides", "ph" )

X = df[["fixed acidity", "volatile acidity", "citric acid", "residual sugar", "density", "sulphates", "alcohol", "quality"]]
y = df["wine type"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

norm = MinMaxScaler().fit(X_train)
# transform training data
X_train_norm = norm.transform(X_train)
# transform testing dataabs
X_test_norm = norm.transform(X_test)

lr = LogisticRegression(solver='lbfgs', max_iter=2000)
lr.fit(X_train, y_train)
pred_lr = lr.predict(X_test)

print("result without sulfur variables: ")
print("Confusion matrix:")
print(confusion_matrix(y_test, pred_lr))
print("Accuracy score:", accuracy_score(y_test, pred_lr))
print(classification_report(y_test, pred_lr, target_names=["white","red"]))

result without sulfur variables: 
Confusion matrix:
[[937  22]
 [ 42 299]]
Accuracy score: 0.9507692307692308
              precision    recall  f1-score   support

       white       0.96      0.98      0.97       959
         red       0.93      0.88      0.90       341

    accuracy                           0.95      1300
   macro avg       0.94      0.93      0.94      1300
weighted avg       0.95      0.95      0.95      1300



In [61]:
# without sulfur variables and chlorides variable ("free sulfur dioxide", "total sulfur dioxide", "chlorides"
# "fixed acidity", "citric acid","volatile acidity", )

X = df[["residual sugar", "density", 
      "pH", "sulphates", "alcohol", "quality"]]
y = df["wine type"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

norm = MinMaxScaler().fit(X_train)
# transform training data
X_train_norm = norm.transform(X_train)
# transform testing dataabs
X_test_norm = norm.transform(X_test)

lr = LogisticRegression(solver='lbfgs', max_iter=2000)
lr.fit(X_train, y_train)
pred_lr = lr.predict(X_test)

print("result without sulfur variables: ")
print("Confusion matrix:")
print(confusion_matrix(y_test, pred_lr))
print("Accuracy score:", accuracy_score(y_test, pred_lr))
print(classification_report(y_test, pred_lr, target_names=["white","red"]))

result without sulfur variables: 
Confusion matrix:
[[896  63]
 [150 191]]
Accuracy score: 0.8361538461538461
              precision    recall  f1-score   support

       white       0.86      0.93      0.89       959
         red       0.75      0.56      0.64       341

    accuracy                           0.84      1300
   macro avg       0.80      0.75      0.77      1300
weighted avg       0.83      0.84      0.83      1300



# Machine learning Modell with RandomForestClassifier

Goal is: determine which varialbe combination affects on the quality of wine

In [65]:
from sklearn.ensemble import RandomForestClassifier

X = df[["fixed acidity", "volatile acidity", "citric acid", "residual sugar", "chlorides", "free sulfur dioxide",
               "total sulfur dioxide", "density", "pH", "sulphates", "alcohol", "quality"]]
y = df["wine type"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

norm = MinMaxScaler().fit(X_train)
# transform training data
X_train_norm = norm.transform(X_train)
# transform testing data
X_test_norm = norm.transform(X_test)

rf = RandomForestClassifier(random_state=0)
rf.fit(X_train, y_train)
pred_lr = rf.predict(X_test)

print("result without acidity variables: ")
print("Confusion matrix:")
print(confusion_matrix(y_test, pred_lr))
print("Accuracy score:", accuracy_score(y_test, pred_lr))
print(classification_report(y_test, pred_lr, target_names=["White","Red"]))

result without acidity variables: 
Confusion matrix:
[[958   1]
 [  6 335]]
Accuracy score: 0.9946153846153846
              precision    recall  f1-score   support

       White       0.99      1.00      1.00       959
         Red       1.00      0.98      0.99       341

    accuracy                           0.99      1300
   macro avg       1.00      0.99      0.99      1300
weighted avg       0.99      0.99      0.99      1300

