In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [2]:
df_red = pd.read_csv("winequality-red.csv", sep = ";")
df_white = pd.read_csv("winequality-white.csv", sep = ";")

In [3]:
df_red["wine type"] = 1
df_red

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  wine type  
0         9.4        5          1  
1         9.8        5          1  
2         9.8        5          1  
3         9.8        6          1  
4         9.4        5          1  
...       ...      ...        ...  
1594     10.5        5          1  
1595     11.2        6          1  
1596     11.0        6          1  
1597     10.2        5          1  
1598     11.0        6          1  

[1599 rows x 13 columns]

In [4]:
df_white["wine type"] = 0
df_white

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  wine type  
0         8.8        6          0  
1         9.5        6          0  
2        10.1        6          0  
3         9.9        6          0  
4         9.9        6          0  
...       ...      ...        ...  
4893     11.2        6          0  
4894      9.6        5          0  
4895      9.4        6          0  
4896     12.8        7          0  
4897     11.8        6          0  

[4898 rows x 13 columns]

In [5]:
df_red["quality_label"] = df_red["quality"].apply(lambda value: "0"
if value <= 5 else '1'
if value <= 7 else '2')
df_red

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  wine type quality_label  
0         9.4        5          1             0  
1         9.8        5          1             0  
2         9.8        5          1             0  
3         9.8        6          1             1  
4         9.4        5          1             0  
...       ...      ...        ...           ...  
1594     10.5        5          1             0  
1595     11.2        6          1             1  
1596     11.0        6          1             1  
1597     10.2        5          1             0  
1598     11.0        6          1             1  

[1599 rows x 14 columns]

In [6]:
df_white["quality_label"] = df_white["quality"].apply(lambda value: "0"
if value <= 5 else '1'
if value <= 7 else '2')
df_white

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  wine type quality_label  
0         8.8        6          0             1  
1         9.5        6          0             1  
2        10.1        6          0             1  
3         9.9        6          0             1  
4         9.9        6          0             1  
...       ...      ...        ...           ...  
4893     11.2        6          0             1  
4894      9.6        5          0             0  
4895      9.4        6          0             1  
4896     12.8        7          0             1  
4897     11.8        6          0             1  

[4898 rows x 14 columns]

# logistic regression

 Goal :  determine the wine type(white is 0, red is 1) from the different composition with logisitic regression

to prepare the dataframe: concatenate white and red wine dataframe

In [7]:
df = pd.concat([df_red,df_white], axis = 0, ignore_index=True)
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4              0.70         0.00             1.9      0.076   
1               7.8              0.88         0.00             2.6      0.098   
2               7.8              0.76         0.04             2.3      0.092   
3              11.2              0.28         0.56             1.9      0.075   
4               7.4              0.70         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
6492            6.2              0.21         0.29             1.6      0.039   
6493            6.6              0.32         0.36             8.0      0.047   
6494            6.5              0.24         0.19             1.2      0.041   
6495            5.5              0.29         0.30             1.1      0.022   
6496            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
6492                 24.0                  92.0  0.99114  3.27       0.50   
6493                 57.0                 168.0  0.99490  3.15       0.46   
6494                 30.0                 111.0  0.99254  2.99       0.46   
6495                 20.0                 110.0  0.98869  3.34       0.38   
6496                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  wine type quality_label  
0         9.4        5          1             0  
1         9.8        5          1             0  
2         9.8        5          1             0  
3         9.8        6          1             1  
4         9.4        5          1             0  
...       ...      ...        ...           ...  
6492     11.2        6          0             1  
6493      9.6        5          0             0  
6494      9.4        6          0             1  
6495     12.8        7          0             1  
6496     11.8        6          0             1  

[6497 rows x 14 columns]

2. define variables into features and target. 

In [25]:
# X are the variables used to predict the wine type.
# y is the prediction variable. 

X = df[["fixed acidity", "volatile acidity", "citric acid", "residual sugar", "chlorides", "free sulfur dioxide",
               "total sulfur dioxide", "density", "pH", "sulphates", "alcohol", "quality"]]
y = df["wine type"]

In [26]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         6497 non-null   float64
 1   volatile acidity      6497 non-null   float64
 2   citric acid           6497 non-null   float64
 3   residual sugar        6497 non-null   float64
 4   chlorides             6497 non-null   float64
 5   free sulfur dioxide   6497 non-null   float64
 6   total sulfur dioxide  6497 non-null   float64
 7   density               6497 non-null   float64
 8   pH                    6497 non-null   float64
 9   sulphates             6497 non-null   float64
 10  alcohol               6497 non-null   float64
 11  quality               6497 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 609.2 KB


In [27]:
X.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [28]:
y

0       1
1       1
2       1
3       1
4       1
       ..
6492    0
6493    0
6494    0
6495    0
6496    0
Name: wine type, Length: 6497, dtype: int64

In [29]:
# Split the data to test and train
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
display(X_train.head(2))
display(X_test.head(2))
display(y_train.head(2))
display(y_test.head(2))

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1916            6.6              0.24         0.35             7.7      0.031   
947             8.3              0.28         0.48             2.1      0.093   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1916                 36.0                 135.0  0.99380  3.19       0.37   
947                   6.0                  12.0  0.99408  3.26       0.62   

      alcohol  quality  
1916     10.5        5  
947      12.4        7

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
3103            7.0              0.17         0.74            12.8      0.045   
1419            7.7              0.64         0.21             2.2      0.077   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
3103                 24.0                 126.0   0.9942  3.26       0.38   
1419                 32.0                 133.0   0.9956  3.27       0.45   

      alcohol  quality  
3103     12.2        8  
1419      9.9        5

1916    0
947     1
Name: wine type, dtype: int64

3103    0
1419    1
Name: wine type, dtype: int64

4. Normalizse or Standardize the train and test after splitting. 

In [30]:
# data normalization with sklearn
from sklearn.preprocessing import MinMaxScaler

# fit scaler on training data
norm = MinMaxScaler().fit(X_train)

# transform training data
X_train_norm = norm.transform(X_train)

# transform testing dataabs
X_test_norm = norm.transform(X_test)

print(norm)
print(X_train_norm)
print(X_test_norm)

MinMaxScaler()
[[0.23728814 0.10666667 0.28455285 ... 0.08426966 0.40322581 0.33333333]
 [0.38135593 0.13333333 0.3902439  ... 0.2247191  0.70967742 0.66666667]
 [0.33050847 0.42333333 0.00813008 ... 0.19662921 0.61290323 0.5       ]
 ...
 [0.22033898 0.19333333 0.16260163 ... 0.11797753 0.24193548 0.33333333]
 [0.22881356 0.12       0.40650407 ... 0.14044944 0.24193548 0.33333333]
 [0.28813559 0.36       0.04878049 ... 0.17977528 0.24193548 0.33333333]]
[[0.27118644 0.06       0.60162602 ... 0.08988764 0.67741935 0.83333333]
 [0.33050847 0.37333333 0.17073171 ... 0.12921348 0.30645161 0.33333333]
 [0.25423729 0.20666667 0.27642276 ... 0.12359551 0.64516129 0.66666667]
 ...
 [0.23728814 0.05333333 0.28455285 ... 0.29775281 0.70967742 0.66666667]
 [0.23728814 0.20666667 0.30894309 ... 0.19662921 0.22580645 0.5       ]
 [0.30508475 0.05333333 0.2195122  ... 0.11797753 0.11290323 0.66666667]]



5. Fit the model

In [33]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(solver='lbfgs', max_iter=2000)
lr.fit(X_train, y_train)

LogisticRegression(max_iter=2000)

6. Make predictions

In [34]:

pred_lr = lr.predict(X_test)

7. Evaluate the model

In [35]:
from sklearn.metrics import confusion_matrix

print("Confusion matrix:")
print(confusion_matrix(y_test, pred_lr))

Confusion matrix:
[[951   8]
 [ 19 322]]


In [36]:
from sklearn.metrics import accuracy_score

print("Accuracy score:", accuracy_score(y_test, pred_lr))

Accuracy score: 0.9792307692307692


In [37]:
from sklearn.metrics import classification_report

print(classification_report(y_test, pred_lr, target_names=["White","red"]))

              precision    recall  f1-score   support

         Red       0.98      0.99      0.99       959
       White       0.98      0.94      0.96       341

    accuracy                           0.98      1300
   macro avg       0.98      0.97      0.97      1300
weighted avg       0.98      0.98      0.98      1300



In [152]:
# with all variables

X = df[["fixed acidity", "volatile acidity", "citric acid", "residual sugar","chlorides", "free sulfur dioxide",
               "total sulfur dioxide", "density", "pH", "sulphates", "alcohol"]]
y = df["wine type"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

norm = MinMaxScaler().fit(X_train)
# transform training data
X_train_norm = norm.transform(X_train)
# transform testing data
X_test_norm = norm.transform(X_test)

lr = LogisticRegression(solver='lbfgs', max_iter=2000)
lr.fit(X_train_norm, y_train)
pred_lr = lr.predict(X_test_norm)

print("result without acidity variables: ")
print("Confusion matrix:")
print(confusion_matrix(y_test, pred_lr))
print("Accuracy score:", accuracy_score(y_test, pred_lr))
print(classification_report(y_test, pred_lr, target_names=["White","Red"]))

result without acidity variables: 
Confusion matrix:
[[955   4]
 [ 18 323]]
Accuracy score: 0.9830769230769231
              precision    recall  f1-score   support

       White       0.98      1.00      0.99       959
         Red       0.99      0.95      0.97       341

    accuracy                           0.98      1300
   macro avg       0.98      0.97      0.98      1300
weighted avg       0.98      0.98      0.98      1300



In [153]:
# without "chlorides"

X = df[["fixed acidity", "volatile acidity", "citric acid", "residual sugar", "free sulfur dioxide",
               "total sulfur dioxide", "density", "pH", "sulphates", "alcohol"]]
y = df["wine type"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

norm = MinMaxScaler().fit(X_train)
# transform training data
X_train_norm = norm.transform(X_train)
# transform testing data
X_test_norm = norm.transform(X_test)

lr = LogisticRegression(solver='lbfgs', max_iter=2000)
lr.fit(X_train_norm, y_train)
pred_lr = lr.predict(X_test_norm)

print("result without acidity variables: ")
print("Confusion matrix:")
print(confusion_matrix(y_test, pred_lr))
print("Accuracy score:", accuracy_score(y_test, pred_lr))
print(classification_report(y_test, pred_lr, target_names=["White","Red"]))

result without acidity variables: 
Confusion matrix:
[[953   6]
 [ 21 320]]
Accuracy score: 0.9792307692307692
              precision    recall  f1-score   support

       White       0.98      0.99      0.99       959
         Red       0.98      0.94      0.96       341

    accuracy                           0.98      1300
   macro avg       0.98      0.97      0.97      1300
weighted avg       0.98      0.98      0.98      1300



In [154]:
# without sulphates

X = df[["fixed acidity", "volatile acidity", "citric acid", "residual sugar","chlorides", "free sulfur dioxide",
               "total sulfur dioxide", "density", "pH", "alcohol"]]
y = df["wine type"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

norm = MinMaxScaler().fit(X_train)
# transform training data
X_train_norm = norm.transform(X_train)
# transform testing data
X_test_norm = norm.transform(X_test)

lr = LogisticRegression(solver='lbfgs', max_iter=2000)
lr.fit(X_train_norm, y_train)
pred_lr = lr.predict(X_test_norm)

print("result without acidity variables: ")
print("Confusion matrix:")
print(confusion_matrix(y_test, pred_lr))
print("Accuracy score:", accuracy_score(y_test, pred_lr))
print(classification_report(y_test, pred_lr, target_names=["White","Red"]))

result without acidity variables: 
Confusion matrix:
[[950   9]
 [ 21 320]]
Accuracy score: 0.9769230769230769
              precision    recall  f1-score   support

       White       0.98      0.99      0.98       959
         Red       0.97      0.94      0.96       341

    accuracy                           0.98      1300
   macro avg       0.98      0.96      0.97      1300
weighted avg       0.98      0.98      0.98      1300



In [155]:
# without sulphates and chlorides

X = df[["fixed acidity", "volatile acidity", "citric acid", "residual sugar", "free sulfur dioxide",
               "total sulfur dioxide", "density", "pH", "alcohol"]]
y = df["wine type"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

norm = MinMaxScaler().fit(X_train)
# transform training data
X_train_norm = norm.transform(X_train)
# transform testing data
X_test_norm = norm.transform(X_test)

lr = LogisticRegression(solver='lbfgs', max_iter=2000)
lr.fit(X_train_norm, y_train)
pred_lr = lr.predict(X_test_norm)

print("result without acidity variables: ")
print("Confusion matrix:")
print(confusion_matrix(y_test, pred_lr))
print("Accuracy score:", accuracy_score(y_test, pred_lr))
print(classification_report(y_test, pred_lr, target_names=["White","Red"]))

result without acidity variables: 
Confusion matrix:
[[949  10]
 [ 26 315]]
Accuracy score: 0.9723076923076923
              precision    recall  f1-score   support

       White       0.97      0.99      0.98       959
         Red       0.97      0.92      0.95       341

    accuracy                           0.97      1300
   macro avg       0.97      0.96      0.96      1300
weighted avg       0.97      0.97      0.97      1300



In [148]:
# without acidity variables ("fixed acidity", "volatile acidity", "citric acid", )

X = df[["residual sugar", "chlorides", "free sulfur dioxide",
               "total sulfur dioxide", "density", "pH", "sulphates", "alcohol", "quality"]]
y = df["wine type"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

norm = MinMaxScaler().fit(X_train)
# transform training data
X_train_norm = norm.transform(X_train)
# transform testing data
X_test_norm = norm.transform(X_test)

lr = LogisticRegression(solver='lbfgs', max_iter=2000)
lr.fit(X_train_norm, y_train)
pred_lr = lr.predict(X_test_norm)

print("result without acidity variables: ")
print("Confusion matrix:")
print(confusion_matrix(y_test, pred_lr))
print("Accuracy score:", accuracy_score(y_test, pred_lr))
print(classification_report(y_test, pred_lr, target_names=["White","Red"]))


result without acidity variables: 
Confusion matrix:
[[949  10]
 [ 35 306]]
Accuracy score: 0.9653846153846154
              precision    recall  f1-score   support

       White       0.96      0.99      0.98       959
         Red       0.97      0.90      0.93       341

    accuracy                           0.97      1300
   macro avg       0.97      0.94      0.95      1300
weighted avg       0.97      0.97      0.96      1300



In [149]:
# without sulfur variables ("free sulfur dioxide", "total sulfur dioxide" )

X = df[["fixed acidity", "volatile acidity", "citric acid", "residual sugar", "chlorides", "density", 
      "pH", "sulphates", "alcohol", "quality"]]
y = df["wine type"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

norm = MinMaxScaler().fit(X_train)
# transform training data
X_train_norm = norm.transform(X_train)
# transform testing dataabs
X_test_norm = norm.transform(X_test)

lr = LogisticRegression(solver='lbfgs', max_iter=2000)
lr.fit(X_train_norm, y_train)
pred_lr = lr.predict(X_test_norm)

print("result without sulfur variables: ")
print("Confusion matrix:")
print(confusion_matrix(y_test, pred_lr))
print("Accuracy score:", accuracy_score(y_test, pred_lr))
print(classification_report(y_test, pred_lr, target_names=["Red","White"]))

result without sulfur variables: 
Confusion matrix:
[[949  10]
 [ 20 321]]
Accuracy score: 0.9769230769230769
              precision    recall  f1-score   support

         Red       0.98      0.99      0.98       959
       White       0.97      0.94      0.96       341

    accuracy                           0.98      1300
   macro avg       0.97      0.97      0.97      1300
weighted avg       0.98      0.98      0.98      1300



In [114]:
# without sulfur variables and chlorides variable ("free sulfur dioxide", "total sulfur dioxide", "chlorides" )

X = df[["fixed acidity", "volatile acidity", "citric acid", "residual sugar", "density", 
      "pH", "sulphates", "alcohol"]]
y = df["wine type"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

norm = MinMaxScaler().fit(X_train)
# transform training data
X_train_norm = norm.transform(X_train)
# transform testing dataabs
X_test_norm = norm.transform(X_test)

lr = LogisticRegression(solver='lbfgs', max_iter=2000)
lr.fit(X_train, y_train)
pred_lr = lr.predict(X_test)

print("result without sulfur variables: ")
print("Confusion matrix:")
print(confusion_matrix(y_test, pred_lr))
print("Accuracy score:", accuracy_score(y_test, pred_lr))
print(classification_report(y_test, pred_lr, target_names=["White","Red"]))

result without sulfur variables: 
Confusion matrix:
[[941  18]
 [ 22 319]]
Accuracy score: 0.9692307692307692
              precision    recall  f1-score   support

       White       0.98      0.98      0.98       959
         Red       0.95      0.94      0.94       341

    accuracy                           0.97      1300
   macro avg       0.96      0.96      0.96      1300
weighted avg       0.97      0.97      0.97      1300



In [113]:
# without sulfur variables and chlorides variable ("free sulfur dioxide", "total sulfur dioxide", "chlorides", "ph" )

X = df[["fixed acidity", "volatile acidity", "citric acid", "residual sugar", "density", "sulphates", "alcohol"]]
y = df["wine type"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

norm = MinMaxScaler().fit(X_train)
# transform training data
X_train_norm = norm.transform(X_train)
# transform testing dataabs
X_test_norm = norm.transform(X_test)

lr = LogisticRegression(solver='lbfgs', max_iter=2000)
lr.fit(X_train_norm, y_train)
pred_lr = lr.predict(X_test_norm)

print("result without sulfur variables: ")
print("Confusion matrix:")
print(confusion_matrix(y_test, pred_lr))
print("Accuracy score:", accuracy_score(y_test, pred_lr))
print(classification_report(y_test, pred_lr, target_names=["white","red"]))
print(y_test)
print(pred_lr)

result without sulfur variables: 
Confusion matrix:
[[944  15]
 [ 41 300]]
Accuracy score: 0.9569230769230769
              precision    recall  f1-score   support

       white       0.96      0.98      0.97       959
         red       0.95      0.88      0.91       341

    accuracy                           0.96      1300
   macro avg       0.96      0.93      0.94      1300
weighted avg       0.96      0.96      0.96      1300

3103    0
1419    1
4761    0
4690    0
4032    0
       ..
889     1
2850    0
4917    0
5198    0
5643    0
Name: wine type, Length: 1300, dtype: int64
[0 1 0 ... 0 0 0]


In [112]:
# without sulfur variables and chlorides variable ("free sulfur dioxide", "total sulfur dioxide", "chlorides"
# "fixed acidity", "citric acid","volatile acidity", )

X = df[["residual sugar", "density", 
      "pH", "sulphates", "alcohol"]]
y = df["wine type"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

norm = MinMaxScaler().fit(X_train)
# transform training data
X_train_norm = norm.transform(X_train)
# transform testing dataabs
X_test_norm = norm.transform(X_test)

lr = LogisticRegression(solver='lbfgs', max_iter=2000)
lr.fit(X_train_norm, y_train)
pred_lr = lr.predict(X_test_norm)

print("result without sulfur variables: ")
print("Confusion matrix:")
print(confusion_matrix(y_test, pred_lr))
print("Accuracy score:", accuracy_score(y_test, pred_lr))
print(classification_report(y_test, pred_lr, target_names=["white","red"]))

result without sulfur variables: 
Confusion matrix:
[[944  15]
 [ 92 249]]
Accuracy score: 0.9176923076923077
              precision    recall  f1-score   support

       white       0.91      0.98      0.95       959
         red       0.94      0.73      0.82       341

    accuracy                           0.92      1300
   macro avg       0.93      0.86      0.88      1300
weighted avg       0.92      0.92      0.91      1300



In [111]:
X = df[["residual sugar", "density", 
      "pH", "sulphates", "alcohol"]]
y = df["wine type"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

norm = MinMaxScaler().fit(X_train)
# transform training data
X_train_norm = norm.transform(X_train)
# transform testing dataabs
X_test_norm = norm.transform(X_test)

lr = LogisticRegression(solver='lbfgs', max_iter=2000)
lr.fit(X_train_norm, y_train)
pred_lr = lr.predict(X_test_norm)

print("result without sulfur variables: ")
print("Confusion matrix:")
print(confusion_matrix(y_test, pred_lr))
print("Accuracy score:", accuracy_score(y_test, pred_lr))
print(classification_report(y_test, pred_lr, target_names=["white","red"]))

result without sulfur variables: 
Confusion matrix:
[[944  15]
 [ 92 249]]
Accuracy score: 0.9176923076923077
              precision    recall  f1-score   support

       white       0.91      0.98      0.95       959
         red       0.94      0.73      0.82       341

    accuracy                           0.92      1300
   macro avg       0.93      0.86      0.88      1300
weighted avg       0.92      0.92      0.91      1300



In [110]:
# only with alcoho, density, residual sugar
X = df[["residual sugar", "density", "alcohol"]]
y = df["wine type"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

norm = MinMaxScaler().fit(X_train)
# transform training data
X_train_norm = norm.transform(X_train)
# transform testing dataabs
X_test_norm = norm.transform(X_test)

lr = LogisticRegression(solver='lbfgs', max_iter=2000)
lr.fit(X_train_norm, y_train)
pred_lr = lr.predict(X_test_norm)

print("result without sulfur variables: ")
print("Confusion matrix:")
print(confusion_matrix(y_test, pred_lr))
print("Accuracy score:", accuracy_score(y_test, pred_lr))
print(classification_report(y_test, pred_lr, target_names=["white","red"]))

result without sulfur variables: 
Confusion matrix:
[[958   1]
 [113 228]]
Accuracy score: 0.9123076923076923
              precision    recall  f1-score   support

       white       0.89      1.00      0.94       959
         red       1.00      0.67      0.80       341

    accuracy                           0.91      1300
   macro avg       0.95      0.83      0.87      1300
weighted avg       0.92      0.91      0.91      1300



#  RandomForestClassifier

Goal is: determine which varialbe combination affects on the quality of wine

In [107]:
from sklearn.ensemble import RandomForestClassifier

X = df[["fixed acidity", "volatile acidity", "citric acid", "residual sugar", "chlorides", "free sulfur dioxide",
               "total sulfur dioxide", "density", "pH", "sulphates", "alcohol"]]
y = df["quality_label"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

""" norm = MinMaxScaler().fit(X_train)
# transform training data
X_train_norm = norm.transform(X_train)
# transform testing data
X_test_norm = norm.transform(X_test) """

rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)
pred_lr = rf.predict(X_test)

print("result without acidity variables: ")
print("Confusion matrix:")
print(confusion_matrix(y_test, pred_lr))
print("Accuracy score:", accuracy_score(y_test, pred_lr))
print(classification_report(y_test, pred_lr, target_names=["low","medium", "high"]))

result without acidity variables: 
Confusion matrix:
[[337 114   0]
 [119 691   2]
 [  0  25  12]]
Accuracy score: 0.8
              precision    recall  f1-score   support

         low       0.74      0.75      0.74       451
      medium       0.83      0.85      0.84       812
        high       0.86      0.32      0.47        37

    accuracy                           0.80      1300
   macro avg       0.81      0.64      0.69      1300
weighted avg       0.80      0.80      0.80      1300



In [108]:
from sklearn.ensemble import RandomForestClassifier

X = df[["fixed acidity", "volatile acidity", "citric acid", "residual sugar", "free sulfur dioxide",
               "total sulfur dioxide", "density", "pH", "sulphates", "alcohol"]]
y = df["quality_label"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

""" norm = MinMaxScaler().fit(X_train)
# transform training data
X_train_norm = norm.transform(X_train)
# transform testing data
X_test_norm = norm.transform(X_test) """

rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)
pred_lr = rf.predict(X_test)

print("result without acidity variables: ")
print("Confusion matrix:")
print(confusion_matrix(y_test, pred_lr))
print("Accuracy score:", accuracy_score(y_test, pred_lr))
print(classification_report(y_test, pred_lr, target_names=["low","medium", "high"]))

result without acidity variables: 
Confusion matrix:
[[330 121   0]
 [107 703   2]
 [  0  25  12]]
Accuracy score: 0.8038461538461539
              precision    recall  f1-score   support

         low       0.76      0.73      0.74       451
      medium       0.83      0.87      0.85       812
        high       0.86      0.32      0.47        37

    accuracy                           0.80      1300
   macro avg       0.81      0.64      0.69      1300
weighted avg       0.80      0.80      0.80      1300



In [109]:
X = df_red[["residual sugar", "density", "alcohol", "pH"]]
y = df_red["quality_label"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=0) #split data
clf = RandomForestClassifier(random_state=0) # 
clf.fit(X_train, y_train) # train the data この2行で学習用のデータで学習が出来る
pred = clf.predict(X_test) # predict the data モデルの精度を確認できる
accuracy = accuracy_score(y_test, pred) # evaluate estimete the data


print(len(X_train)) #amount of train data
print(len(X_test)) # amount of test data

print(f"accuracy score: ",accuracy)
print(f"train score: {clf.score(X_train, y_train)}")
print(f"test score: {clf.score(X_test, y_test)}")
print(classification_report(y_test, pred, target_names=["low","medium", "high"]))

1279
320
accuracy score:  0.771875
train score: 1.0
test score: 0.771875
              precision    recall  f1-score   support

         low       0.76      0.78      0.77       148
      medium       0.79      0.78      0.79       169
        high       0.00      0.00      0.00         3

    accuracy                           0.77       320
   macro avg       0.52      0.52      0.52       320
weighted avg       0.77      0.77      0.77       320



In [115]:
X = df_white[["residual sugar", "density", "alcohol", "pH"]]
y = df_white["quality_label"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=0) #split data
clf = RandomForestClassifier(random_state=0) # 
clf.fit(X_train, y_train) # train the data この2行で学習用のデータで学習が出来る
pred = clf.predict(X_test) # predict the data モデルの精度を確認できる
accuracy = accuracy_score(y_test, pred) # evaluate estimete the data


print(len(X_train)) #amount of train data
print(len(X_test)) # amount of test data

print(f"accuracy score: ",accuracy)
print(f"train score: {clf.score(X_train, y_train)}")
print(f"test score: {clf.score(X_test, y_test)}")
print(classification_report(y_test, pred, target_names=["low","medium", "high"]))

3918
980
accuracy score:  0.7683673469387755
train score: 0.9997447677386422
test score: 0.7683673469387755
              precision    recall  f1-score   support

         low       0.78      0.61      0.68       355
      medium       0.76      0.90      0.82       592
        high       0.89      0.24      0.38        33

    accuracy                           0.77       980
   macro avg       0.81      0.58      0.63       980
weighted avg       0.77      0.77      0.76       980



#  SVM(support vector maschine)

In [106]:
from sklearn.svm import LinearSVC

X = df_red[["fixed acidity", "volatile acidity", "citric acid", "residual sugar", "free sulfur dioxide",
               "total sulfur dioxide", "density", "pH", "sulphates", "alcohol"]]
y = df_red["quality_label"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=0) #split data
clf = LinearSVC() # 
clf.fit(X_train, y_train)
pred = clf.predict(X_test) 
accuracy = accuracy_score(y_test, pred) 


print(len(X_train)) #amount of train data
print(len(X_test)) # amount of test data

print(f"accuracy score: ",accuracy)
print(f"train score: {clf.score(X_train, y_train)}")
print(f"test score: {clf.score(X_test, y_test)}")
print(classification_report(y_test, pred))
print(classification_report(y_test, pred, target_names=["low","medium", "high"]))

1279
320
accuracy score:  0.746875
train score: 0.72556684910086
test score: 0.746875
              precision    recall  f1-score   support

           0       0.77      0.68      0.72       148
           1       0.73      0.82      0.77       169
           2       0.00      0.00      0.00         3

    accuracy                           0.75       320
   macro avg       0.50      0.50      0.50       320
weighted avg       0.74      0.75      0.74       320

              precision    recall  f1-score   support

         low       0.77      0.68      0.72       148
      medium       0.73      0.82      0.77       169
        high       0.00      0.00      0.00         3

    accuracy                           0.75       320
   macro avg       0.50      0.50      0.50       320
weighted avg       0.74      0.75      0.74       320



c:\Users\satom\anaconda3\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\satom\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\satom\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\satom\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted sam

In [136]:
# same maschine modell, but svm.SVC and normalization

from sklearn import svm

X = df_red[["fixed acidity", "volatile acidity", "citric acid", "residual sugar", "free sulfur dioxide",
               "total sulfur dioxide", "density", "pH", "sulphates", "alcohol"]]
y = df_red["quality_label"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=0) #split data

norm = MinMaxScaler().fit(X_train)
X_train_norm = norm.transform(X_train)
X_test_norm = norm.transform(X_test)

clf = svm.SVC() # 
clf.fit(X_train_norm, y_train) # train the data この2行で学習用のデータで学習が出来る
pred = clf.predict(X_test_norm) # predict the data モデルの精度を確認できる
accuracy = accuracy_score(y_test, pred) # evaluate estimete the data


print(len(X_train)) #amount of train data
print(len(X_test)) # amount of test data

print(f"accuracy score: ",accuracy)
print(f"train score: {clf.score(X_train_norm, y_train)}")
print(f"test score: {clf.score(X_test_norm, y_test)}")

print(classification_report(y_test, pred, target_names=["low","medium", "high"]))


1279
320
accuracy score:  0.746875
train score: 0.7716966379984362
test score: 0.746875
              precision    recall  f1-score   support

         low       0.73      0.74      0.74       148
      medium       0.76      0.76      0.76       169
        high       0.00      0.00      0.00         3

    accuracy                           0.75       320
   macro avg       0.50      0.50      0.50       320
weighted avg       0.74      0.75      0.74       320



c:\Users\satom\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\satom\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\satom\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [103]:
X = df_white[["fixed acidity", "volatile acidity", "citric acid", "residual sugar", "free sulfur dioxide",
               "total sulfur dioxide", "density", "pH", "sulphates", "alcohol"]]
y = df_white["quality_label"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=0) #split data
clf = LinearSVC() # 
clf.fit(X_train, y_train) # train the data この2行で学習用のデータで学習が出来る
pred = clf.predict(X_test) # predict the data モデルの精度を確認できる
accuracy = accuracy_score(y_test, pred) # evaluate estimete the data


print(len(X_train)) #amount of train data
print(len(X_test)) # amount of test data

print(f"accuracy score: ",accuracy)
print(f"train score: {clf.score(X_train, y_train)}")
print(f"test score: {clf.score(X_test, y_test)}")
print(classification_report(y_test, pred, target_names=["low","medium", "high"]))

3673
1225
accuracy score:  0.6391836734693878
train score: 0.6637625918867411
test score: 0.6391836734693878
              precision    recall  f1-score   support

         low       0.84      0.11      0.19       441
      medium       0.63      0.99      0.77       745
        high       0.00      0.00      0.00        39

    accuracy                           0.64      1225
   macro avg       0.49      0.36      0.32      1225
weighted avg       0.69      0.64      0.54      1225



c:\Users\satom\anaconda3\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\satom\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\satom\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\satom\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted sam

In [102]:
from sklearn.svm import LinearSVC

X = df_red[["residual sugar", "total sulfur dioxide", "density", "pH", "alcohol"]]
y = df_red["quality_label"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=0) #split data
clf = LinearSVC() # 
clf.fit(X_train, y_train) # train the data この2行で学習用のデータで学習が出来る
pred = clf.predict(X_test) # predict the data モデルの精度を確認できる
accuracy = accuracy_score(y_test, pred) # evaluate estimete the data


print(len(X_train)) #amount of train data
print(len(X_test)) # amount of test data

print(f"accuracy score: ",accuracy)
print(f"train score: {clf.score(X_train, y_train)}")
print(f"test score: {clf.score(X_test, y_test)}")
print(classification_report(y_test, pred,target_names=["low","medium", "high"]))

1199
400
accuracy score:  0.645
train score: 0.6422018348623854
test score: 0.645
              precision    recall  f1-score   support

         low       0.67      0.52      0.59       185
      medium       0.69      0.77      0.73       210
        high       0.00      0.00      0.00         5

    accuracy                           0.65       400
   macro avg       0.45      0.43      0.44       400
weighted avg       0.67      0.65      0.65       400



c:\Users\satom\anaconda3\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


In [139]:
from sklearn import svm

X = df_red[["residual sugar", "total sulfur dioxide", "density", "pH", "alcohol"]]
y = df_red["quality_label"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=0) #split data

norm = MinMaxScaler().fit(X_train)
X_train_norm = norm.transform(X_train)
X_test_norm = norm.transform(X_test)

clf = svm.SVC() 
clf.fit(X_train_norm, y_train) 
pred = clf.predict(X_test_norm) 
accuracy = accuracy_score(y_test, pred) 


print(len(X_train)) #amount of train data
print(len(X_test)) # amount of test data

print(f"accuracy score: ",accuracy)
print(f"train score: {clf.score(X_train_norm, y_train)}")
print(f"test score: {clf.score(X_test_norm, y_test)}")
print(classification_report(y_test, pred,target_names=["low","medium", "high"]))

1199
400
accuracy score:  0.725
train score: 0.7281067556296914
test score: 0.725
              precision    recall  f1-score   support

         low       0.72      0.70      0.71       185
      medium       0.73      0.77      0.75       210
        high       0.00      0.00      0.00         5

    accuracy                           0.73       400
   macro avg       0.48      0.49      0.49       400
weighted avg       0.72      0.72      0.72       400



c:\Users\satom\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\satom\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\satom\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [101]:
# same in white wine
from sklearn.svm import LinearSVC

X = df_white[["residual sugar", "total sulfur dioxide", "density", "pH", "alcohol"]]
y = df_white["quality_label"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=0) #split data
clf = LinearSVC() # 
clf.fit(X_train, y_train) # train the data この2行で学習用のデータで学習が出来る
pred = clf.predict(X_test) # predict the data モデルの精度を確認できる
accuracy = accuracy_score(y_test, pred) # evaluate estimete the data


print(len(X_train)) #amount of train data
print(len(X_test)) # amount of test data

print(f"accuracy score: ",accuracy)
print(f"train score: {clf.score(X_train, y_train)}")
print(f"test score: {clf.score(X_test, y_test)}")
print(classification_report(y_test, pred, target_names=["low","medium", "high"]))

3673
1225
accuracy score:  0.6522448979591837
train score: 0.6498774843452219
test score: 0.6522448979591837
              precision    recall  f1-score   support

         low       0.57      0.59      0.58       441
      medium       0.73      0.72      0.72       745
        high       0.00      0.00      0.00        39

    accuracy                           0.65      1225
   macro avg       0.43      0.44      0.43      1225
weighted avg       0.65      0.65      0.65      1225



c:\Users\satom\anaconda3\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


In [144]:
#LinearSVC without normalization
X = df[["residual sugar", "total sulfur dioxide", "density", "pH", "alcohol"]]
y = df["quality_label"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=0) #split data

""" norm = MinMaxScaler().fit(X_train)
X_train_norm = norm.transform(X_train)
X_test_norm = norm.transform(X_test) """

clf = LinearSVC()
clf.fit(X_train, y_train) 
pred = clf.predict(X_test) 
accuracy = accuracy_score(y_test, pred) 


print(len(X_train)) #amount of train data
print(len(X_test)) # amount of test data

print(f"accuracy score: ",accuracy)
print(f"train score: {clf.score(X_train, y_train)}")
print(f"test score: {clf.score(X_test, y_test)}")
print(classification_report(y_test, pred,target_names=["low","medium", "high"]))

4872
1625
accuracy score:  0.6313846153846154
train score: 0.6414203612479474
test score: 0.6313846153846154
              precision    recall  f1-score   support

         low       0.62      0.20      0.31       597
      medium       0.63      0.93      0.75       978
        high       0.00      0.00      0.00        50

    accuracy                           0.63      1625
   macro avg       0.42      0.38      0.35      1625
weighted avg       0.61      0.63      0.56      1625



c:\Users\satom\anaconda3\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\satom\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\satom\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\satom\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted sam

In [143]:
#  LiearSVC with normalization
X = df[["residual sugar", "total sulfur dioxide", "density", "pH", "alcohol"]]
y = df["quality_label"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=0) #split data

norm = MinMaxScaler().fit(X_train)
X_train_norm = norm.transform(X_train)
X_test_norm = norm.transform(X_test)

clf = LinearSVC()
clf.fit(X_train_norm, y_train) 
pred = clf.predict(X_test_norm) 
accuracy = accuracy_score(y_test, pred) 


print(len(X_train)) #amount of train data
print(len(X_test)) # amount of test data

print(f"accuracy score: ",accuracy)
print(f"train score: {clf.score(X_train_norm, y_train)}")
print(f"test score: {clf.score(X_test_norm, y_test)}")
print(classification_report(y_test, pred,target_names=["low","medium", "high"]))

4872
1625
accuracy score:  0.6584615384615384
train score: 0.6767241379310345
test score: 0.6584615384615384
              precision    recall  f1-score   support

         low       0.58      0.51      0.54       597
      medium       0.70      0.78      0.74       978
        high       0.00      0.00      0.00        50

    accuracy                           0.66      1625
   macro avg       0.43      0.43      0.43      1625
weighted avg       0.63      0.66      0.64      1625



c:\Users\satom\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\satom\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\satom\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [140]:
from sklearn import svm

X = df[["residual sugar", "total sulfur dioxide", "density", "pH", "alcohol"]]
y = df["quality_label"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=0) #split data

norm = MinMaxScaler().fit(X_train)
X_train_norm = norm.transform(X_train)
X_test_norm = norm.transform(X_test)

clf = svm.SVC() 
clf.fit(X_train_norm, y_train) 
pred = clf.predict(X_test_norm) 
accuracy = accuracy_score(y_test, pred) 


print(len(X_train)) #amount of train data
print(len(X_test)) # amount of test data

print(f"accuracy score: ",accuracy)
print(f"train score: {clf.score(X_train_norm, y_train)}")
print(f"test score: {clf.score(X_test_norm, y_test)}")
print(classification_report(y_test, pred,target_names=["low","medium", "high"]))

4872
1625
accuracy score:  0.6676923076923077
train score: 0.6982758620689655
test score: 0.6676923076923077
              precision    recall  f1-score   support

         low       0.61      0.48      0.54       597
      medium       0.69      0.81      0.75       978
        high       0.00      0.00      0.00        50

    accuracy                           0.67      1625
   macro avg       0.43      0.43      0.43      1625
weighted avg       0.64      0.67      0.65      1625



c:\Users\satom\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\satom\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\satom\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# KneighboursClassifier

for KneighboursClassifier we need to normalize our data. The k-nearest neighbor algorithm relies on majority voting based on class membership of 'k' nearest samples for a given test point. The nearness of samples is typically based on Euclidean distance.

In [122]:
from sklearn.neighbors import KNeighborsClassifier
X = df_white[["fixed acidity", "volatile acidity", "citric acid", "residual sugar","free sulfur dioxide",
               "total sulfur dioxide", "density", "pH", "sulphates", "alcohol"]]
y = df_white["quality_label"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=0) #split data

norm = MinMaxScaler().fit(X_train)
X_train_norm = norm.transform(X_train)
X_test_norm = norm.transform(X_test)

clf = KNeighborsClassifier(n_neighbors=3)
clf.fit(X_train_norm, y_train) # train the data この2行で学習用のデータで学習が出来る
pred = clf.predict(X_test_norm) # predict the data モデルの精度を確認できる
accuracy = accuracy_score(y_test, pred) # evaluate estimete the data


print(len(X_train)) #amount of train data
print(len(X_test)) # amount of test data

print(f"accuracy score: ",accuracy)
print(f"train score: {clf.score(X_train, y_train)}")
print(f"test score: {clf.score(X_test, y_test)}")
print(classification_report(y_test, pred, target_names=["low","medium", "high"]))


c:\Users\satom\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(


3673
1225
accuracy score:  0.7126530612244898
train score: 0.32616389872039203
test score: 0.36
              precision    recall  f1-score   support

         low       0.68      0.58      0.62       441
      medium       0.74      0.82      0.78       745
        high       0.32      0.21      0.25        39

    accuracy                           0.71      1225
   macro avg       0.58      0.53      0.55      1225
weighted avg       0.70      0.71      0.71      1225



c:\Users\satom\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(


In [120]:
from sklearn.neighbors import KNeighborsClassifier
X = df_red[["fixed acidity", "volatile acidity", "citric acid", "residual sugar","chlorides", "free sulfur dioxide",
               "total sulfur dioxide", "density", "pH", "sulphates", "alcohol"]]
y = df_red["quality_label"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=0) #split data

norm = MinMaxScaler().fit(X_train)
X_train_norm = norm.transform(X_train)
X_test_norm = norm.transform(X_test)

clf = KNeighborsClassifier(n_neighbors=3)
clf.fit(X_train_norm, y_train)
pred = clf.predict(X_test_norm) 
accuracy = accuracy_score(y_test, pred)


print(len(X_train)) #amount of train data
print(len(X_test)) # amount of test data

print(f"accuracy score: ",accuracy)
print(f"train score: {clf.score(X_train, y_train)}")
print(f"test score: {clf.score(X_test, y_test)}")
print(classification_report(y_test, pred, target_names=["low","medium", "high"]))

1199
400
accuracy score:  0.6825
train score: 0.5229357798165137
test score: 0.525
              precision    recall  f1-score   support

         low       0.70      0.63      0.66       185
      medium       0.68      0.75      0.71       210
        high       0.00      0.00      0.00         5

    accuracy                           0.68       400
   macro avg       0.46      0.46      0.46       400
weighted avg       0.68      0.68      0.68       400



c:\Users\satom\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(
c:\Users\satom\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(


In [123]:
from sklearn.neighbors import KNeighborsClassifier
X = df[["fixed acidity", "volatile acidity", "citric acid", "residual sugar","chlorides", "free sulfur dioxide",
               "total sulfur dioxide", "density", "pH", "sulphates", "alcohol"]]
y = df["quality_label"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=0) #split data

norm = MinMaxScaler().fit(X_train)
X_train_norm = norm.transform(X_train)
X_test_norm = norm.transform(X_test)

clf = KNeighborsClassifier(n_neighbors=3)
clf.fit(X_train_norm, y_train) 
pred = clf.predict(X_test_norm) 
accuracy = accuracy_score(y_test, pred) 


print(len(X_train))
print(len(X_test))

print(f"accuracy score: ",accuracy)
print(f"train score: {clf.score(X_train, y_train)}")
print(f"test score: {clf.score(X_test, y_test)}")
print(classification_report(y_test, pred, target_names=["low","medium", "high"]))

4872
1625
accuracy score:  0.7064615384615385


c:\Users\satom\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(


train score: 0.36658456486042695
test score: 0.3686153846153846
              precision    recall  f1-score   support

         low       0.66      0.61      0.63       597
      medium       0.75      0.79      0.77       978
        high       0.34      0.24      0.28        50

    accuracy                           0.71      1625
   macro avg       0.58      0.55      0.56      1625
weighted avg       0.70      0.71      0.70      1625



c:\Users\satom\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(


In [126]:
from sklearn.neighbors import KNeighborsClassifier
X = df_white[["fixed acidity", "residual sugar",
               "total sulfur dioxide", "density", "pH", "alcohol"]]
y = df_white["quality_label"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=0) #split data

norm = MinMaxScaler().fit(X_train)
X_train_norm = norm.transform(X_train)
X_test_norm = norm.transform(X_test)

clf = KNeighborsClassifier(n_neighbors=3)
clf.fit(X_train_norm, y_train) 
pred = clf.predict(X_test_norm) 
accuracy = accuracy_score(y_test, pred) 


print(len(X_train)) 
print(len(X_test)) 

print(f"accuracy score: ",accuracy)
print(f"train score: {clf.score(X_train, y_train)}")
print(f"test score: {clf.score(X_test, y_test)}")
print(classification_report(y_test, pred, target_names=["low","medium", "high"]))

3673
1225
accuracy score:  0.6873469387755102


c:\Users\satom\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(


train score: 0.32616389872039203
test score: 0.35918367346938773
              precision    recall  f1-score   support

         low       0.63      0.54      0.58       441
      medium       0.72      0.80      0.76       745
        high       0.33      0.15      0.21        39

    accuracy                           0.69      1225
   macro avg       0.56      0.50      0.52      1225
weighted avg       0.68      0.69      0.68      1225



c:\Users\satom\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(


# Naive Bayes

As Naive Bayes algorithm is based on probability not on distance, so it doesn't require feature scaling

In [129]:
from sklearn.naive_bayes import GaussianNB
X = df_white[["fixed acidity", "volatile acidity", "citric acid", "residual sugar","chlorides", "free sulfur dioxide",
               "total sulfur dioxide", "density", "pH", "sulphates", "alcohol"]]
y = df_white["quality_label"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=0) #split data

clf = GaussianNB()
clf.fit(X_train, y_train) 
pred = clf.predict(X_test) 
accuracy = accuracy_score(y_test, pred) 


print(len(X_train)) 
print(len(X_test)) 

print(f"accuracy score: ",accuracy)
print(f"train score: {clf.score(X_train, y_train)}")
print(f"test score: {clf.score(X_test, y_test)}")
print(classification_report(y_test, pred, target_names=["low","medium", "high"]))

3673
1225
accuracy score:  0.64
train score: 0.6653961339504493
test score: 0.64
              precision    recall  f1-score   support

         low       0.56      0.48      0.52       441
      medium       0.68      0.77      0.72       745
        high       0.08      0.03      0.04        39

    accuracy                           0.64      1225
   macro avg       0.44      0.42      0.43      1225
weighted avg       0.62      0.64      0.63      1225



In [131]:
from sklearn.naive_bayes import GaussianNB
X = df_red[["fixed acidity", "volatile acidity", "citric acid", "residual sugar","chlorides", "free sulfur dioxide",
               "total sulfur dioxide", "density", "pH", "sulphates", "alcohol"]]
y = df_red["quality_label"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=0) #split data

clf = GaussianNB()
clf.fit(X_train, y_train) 
pred = clf.predict(X_test) 
accuracy = accuracy_score(y_test, pred) 


print(len(X_train)) 
print(len(X_test)) 

print(f"accuracy score: ",accuracy)
print(f"train score: {clf.score(X_train, y_train)}")
print(f"test score: {clf.score(X_test, y_test)}")
print(classification_report(y_test, pred, target_names=["low","medium", "high"]))

1199
400
accuracy score:  0.6975
train score: 0.7030859049207673
test score: 0.6975
              precision    recall  f1-score   support

         low       0.70      0.70      0.70       185
      medium       0.71      0.71      0.71       210
        high       0.00      0.00      0.00         5

    accuracy                           0.70       400
   macro avg       0.47      0.47      0.47       400
weighted avg       0.70      0.70      0.70       400



In [132]:
from sklearn.naive_bayes import GaussianNB
X = df[["fixed acidity", "volatile acidity", "citric acid", "residual sugar","chlorides", "free sulfur dioxide",
               "total sulfur dioxide", "density", "pH", "sulphates", "alcohol"]]
y = df["quality_label"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=0) #split data

clf = GaussianNB()
clf.fit(X_train, y_train) 
pred = clf.predict(X_test) 
accuracy = accuracy_score(y_test, pred) 


print(len(X_train)) 
print(len(X_test)) 

print(f"accuracy score: ",accuracy)
print(f"train score: {clf.score(X_train, y_train)}")
print(f"test score: {clf.score(X_test, y_test)}")
print(classification_report(y_test, pred, target_names=["low","medium", "high"]))

4872
1625
accuracy score:  0.6338461538461538
train score: 0.6481937602627258
test score: 0.6338461538461538
              precision    recall  f1-score   support

         low       0.56      0.50      0.52       597
      medium       0.68      0.75      0.71       978
        high       0.21      0.08      0.12        50

    accuracy                           0.63      1625
   macro avg       0.48      0.44      0.45      1625
weighted avg       0.62      0.63      0.62      1625



In [127]:
from sklearn.naive_bayes import GaussianNB
X = df_white[["fixed acidity", "residual sugar",
               "total sulfur dioxide", "density", "pH", "alcohol"]]
y = df_white["quality_label"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=0) #split data

clf = GaussianNB()
clf.fit(X_train, y_train) 
pred = clf.predict(X_test) 
accuracy = accuracy_score(y_test, pred) 


print(len(X_train)) 
print(len(X_test)) 

print(f"accuracy score: ",accuracy)
print(f"train score: {clf.score(X_train, y_train)}")
print(f"test score: {clf.score(X_test, y_test)}")
print(classification_report(y_test, pred, target_names=["low","medium", "high"]))

3673
1225
accuracy score:  0.626938775510204
train score: 0.640620745984209
test score: 0.626938775510204
              precision    recall  f1-score   support

         low       0.52      0.55      0.54       441
      medium       0.69      0.70      0.70       745
        high       0.00      0.00      0.00        39

    accuracy                           0.63      1225
   macro avg       0.41      0.42      0.41      1225
weighted avg       0.61      0.63      0.62      1225



In [133]:
from sklearn.naive_bayes import GaussianNB
X = df_red[["fixed acidity", "residual sugar",
               "total sulfur dioxide", "density", "pH", "alcohol"]]
y = df_red["quality_label"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=0) #split data

clf = GaussianNB()
clf.fit(X_train, y_train) 
pred = clf.predict(X_test) 
accuracy = accuracy_score(y_test, pred) 


print(len(X_train)) 
print(len(X_test)) 

print(f"accuracy score: ",accuracy)
print(f"train score: {clf.score(X_train, y_train)}")
print(f"test score: {clf.score(X_test, y_test)}")
print(classification_report(y_test, pred, target_names=["low","medium", "high"]))

1199
400
accuracy score:  0.705
train score: 0.6972477064220184
test score: 0.705
              precision    recall  f1-score   support

         low       0.68      0.77      0.72       185
      medium       0.74      0.67      0.70       210
        high       0.00      0.00      0.00         5

    accuracy                           0.70       400
   macro avg       0.47      0.48      0.47       400
weighted avg       0.70      0.70      0.70       400



# Decision Tree